# Python DA Assignment 1: Data Analysis using NumPy and Pandas

**Numpy Array Operations:**

**Problem Statement:**

 To learn how to use NumPy for creating arrays, performing basic
array operations, and conducting numerical computations through analyzing
temperature data.

**Scenario:**

You are given a list of daily average temperatures (in degrees Celsius)
recorded over two weeks. Your task is to use NumPy to analyze this data.

**Step wise Instructions:**

**1.Create a 1D NumPy Array:**

Create a 1D NumPy array named temperatures_w1 for Week 1 with the
following values:
[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]

In [2]:
import numpy as np
temperatures_w1=np.array([22.5,25.3,20.8,23.4,26.1,24.8,21.9])
print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

**Imports the NumPy library.np.array()  Creates a NumPy array()
temperatures_w1 Stores the temperatures of seven days.
print() Displays the array.**

**2.Inspection and Properties:**

Inspect the shape, data type, and the number of elements in the array.
Inspect the shape of the temperatures_w1 array.

In [3]:
print("shape:",temperatures_w1.shape)
print("data_type:",temperatures_w1.dtype)
print("number_of_elements:",temperatures_w1.size)

shape: (7,)
data_type: float64
number_of_elements: 7

**shape shows the dimensions of the array.(7,) means the array is one-dimensional and contains seven elements. dtype shows the type of values stored,size shows how many elements are present.**

**3.Array Operations:**

• Convert the temperatures_w1 from Celsius to Fahrenheit using the
formula: Fahrenheit = (Celsius * 9/5) + 32

• Find the maximum, minimum, and mean temperatures for the week.

In [4]:
Fahrenheit = (temperatures_w1 * 9/5) + 32
print(np.round(Fahrenheit, 2))

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]

**The formula converts each temperature from Celsius to Fahrenheit. np.round() displays the values with two decimal places.**

In [5]:
print("Maximum:", np.max(temperatures_w1))
print("Minimum:", np.min(temperatures_w1))
print("Mean:", np.round(np.mean(temperatures_w1), 2))

Maximum: 26.1
Minimum: 20.8
Mean: 23.54

**np.max() finds the highest temperature, np.min() finds the lowest temperature, and np.mean() calculates the average temperature.**

**4.Array Slicing and Indexing:**

• Extract the temperatures for the first three days of the week.

• Extract the temperatures for the weekend (last two days).

• Extract the temperatures for the middle three days of the week.

In [6]:
print(temperatures_w1[:3])

[22.5 25.3 20.8]

**[:3] selects the first three values.Here indexing starts from 0, and the ending index is not included.**

In [7]:
print(temperatures_w1[-2:])

[24.8 21.9]

**[-2:] takes the last two values of the array**

In [8]:
print(temperatures_w1[2:5])

[20.8 23.4 26.1]

**[2:5] selects the elements at index positions 2, 3, and 4.**

**5.Create a 2D Array:**

Create a 2D NumPy array named temperatures where each row represents
temperatures for a different week:

★ Row 1: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] (Week 1)

★ Row 2: [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] (Week 2)

In [9]:
temperatures = np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]

**2D array is created using two lists. The first row represents Week 1 and the second row represents Week 2.**

**6.Inspect and Slice the 2D Array:**

• Inspect and print the shape, data type, and total number of elements in the
temperatures array.

• Extract the temperatures for each week and the weekends (last two days)
for both weeks.

In [10]:
print("Shape:", temperatures.shape)
print("Data_Type:", temperatures.dtype)
print("Total_Elements:", temperatures.size)

Shape: (2, 7)
Data_Type: float64
Total_Elements: 14

**The array contains 2 rows and 7 columns, so its shape is (2, 7). There are 14 temperature values in total.**

In [11]:
print(temperatures[:, -2:])
print("Week 1:", temperatures[0])
print("Week 2:", temperatures[1])

[[24.8 21.9]
 [22.8 20.1]]
Week 1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]

 **The colon : selects all rows, while -2: selects the last two columns. This gives the weekend temperatures for both weeks.temperatures[0] selects the first row, and temperatures[1] selects the second row.**

# Pandas Series:

1.Create a Pandas Series named marks with the following data:

➢ Marks: 95, 92, 89, 85, 80

➢ Custom Indices: 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'

In [12]:
import pandas as pd
marks=pd.Series([95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

**Pandas Series is created to store student marks.Each mark has a custom index label representing the students rank.**

**2.Indexing and Slicing:**

• Use the integer index position to access the mark of the 1st rank student.

• Use the loc accessor to retrieve the marks of the top 3 ranks by
specifying their index labels.

• Use the iloc accessor to retrieve the mark of the 3rd rank student.

• Apply a boolean mask to filter the Series and retrieve the ranks where the
marks are greater than 90.

In [13]:
print(marks.iloc[0])

95

**iloc[0] select the first element based on its position. Indexing starts from zero.**

In [14]:
print(marks.loc['Rank1':'Rank3'])

Rank1    95
Rank2    92
Rank3    89
dtype: int64

**here loc select values using index labels.it retrieves the marks from Rank1 to Rank3.**

In [15]:
print(marks.iloc[2])

89

**iloc[2] retrieve the third value because Python indexing starts at zero.**

In [16]:
print(marks[marks > 90])

Rank1    95
Rank2    92
dtype: int64

**Here the condition "marks>90" check each values and displays only the students who scored more than 90.**

# Manipulating Series:

• Modify the mark of the student with the 1st rank to 100.

• Remove the entry corresponding to the last rank from the Series.

• Compute the CGPA by dividing each mark in the Series by 10.

In [17]:
marks.loc['Rank1'] = 100
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

**loc is used to select Rank1 and update its mark from 95 to 100.**

In [18]:
marks = marks.drop('Rank5')
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

**drop() removes the selected index label**

In [19]:
cgpa = marks / 10
print(cgpa)

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64

**To calculate the CGPA each student's mark is divided by 10**

# Pandas DataFrame:

**1.Creating Pandas DataFrame:**

• Create a Pandas DataFrame named transactions with the following data:

➢ TransactionID: 101, 102, 103, 104, 105, 106, 107, 108, 109, 110

➢ ProductCategory: 'Electronics', 'Clothing', 'Electronics', 'Furniture',
'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'

➢ Region: 'North', 'South', 'North', 'East', 'West', 'North', 'East', 'West',
'South', 'North'

➢ Amount: 200, 150, 300, 450, 200, 250, 300, 180, 350, 400

In [21]:
data={'TransactionID':[101,102,103,104,105,106,107,108,109,110],
      'ProductCategory':['Electronics','Clothing','Electronics',
                        'Furniture','Clothing','Electronics',
                        'Furniture','Clothing','Furniture','Electronics'],
      'Region':['North','South','North','East','West',
               'North','East','West','South','North'],
      'Amount':[200,150,300,450,200,250,300,180,350,400]}
transactions=pd.DataFrame(data)
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

**Here a dictionary is created to store the transaction details.Then the pd.DataFrame() convert the dictionary into a table.**

**2. Data Exploration:**

a) Display the transactions DataFrame and its basic information, including
head, tail, shape, column   names, and data types.

b) Display only the 'ProductCategory' and 'Amount' columns.

c) Retrieve the last 3 columns of the DataFrame using iloc or loc.

d) Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.

e) Find the value counts for the 'ProductCategory' column.

f) Find the unique values in the 'Region' column.

g) Group by 'Region' and find the mean amount for each region.

a) Display the transactions DataFrame and its basic information, including
head, tail, shape, column   names, and data types.

In [22]:
display(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

**display() shows the complete DataFrame in a table format**

In [23]:
transactions.head()

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

**transactions.head() displays the first five rows of the DataFrame.**

In [ ]:
transactions.tail()

**transactions.tail() displays the last five rows of the DataFrame.**

In [24]:
transactions.shape

(10, 4)

**which means the DataFrame contains 10 rows and 4 columns.**

In [25]:
print(transactions.columns)

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')

**print(transactions.columns) displays the names of all columns.**

In [26]:
print(transactions.dtypes)

TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object

**This shows the data type of each column.**

In [27]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    10 non-null     int64
 1   ProductCategory  10 non-null     object
 2   Region           10 non-null     object
 3   Amount           10 non-null     int64
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes

**transactions.info() displays the column names,non-null values,data types and memory usage.**

b) Display only the 'ProductCategory' and 'Amount' columns.

In [28]:
print(transactions[['ProductCategory','Amount']])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

**Here the double square brackets are used to select multiple columns from the DataFrame**.

c)Retrieve the last 3 columns of the DataFrame using iloc or loc.

In [29]:
print(transactions.iloc[:,-3:])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

**iloc is used to select data by position. Here, : selects all rows and -3: selects the last three columns.**

d) Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.

In [30]:
result=transactions[(transactions['Region']=='North')&(transactions['Amount']>200)]
print(result)

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

**Two conditions are applied to filter the data. The & operator checks that both conditions are true. Only transactions from the North region with an amount greater than 200 are displayed.**

e) Find the value counts for the 'ProductCategory' column.

In [31]:
print(transactions['ProductCategory'].value_counts())

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

**value_counts() count howmany times each product category appears in the column.**

f) Find the unique values in the 'Region' column.

In [32]:
print(transactions['Region'].unique())

['North' 'South' 'East' 'West']

**unique() displays the different region names without repeating any values.**

g) Group by 'Region' and find the mean amount for each region.

In [33]:
print(transactions.groupby('Region')['Amount'].mean())

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

**groupby() groups the transactions based on region. Then mean() calculates the average transaction amount for each region.**

**3. Manipulating the DataFrame:**

a) Modify the 'Amount' for the transaction with TransactionID 102 to 165.

b) Add a new column 'Discount' by calculating 10% of the 'Amount'.

c) Remove the row with TransactionID 109.

d) Delete the 'Discount' column from the DataFrame.

a) Modify the 'Amount' for the transaction with TransactionID 102 to 165.

In [34]:
transactions.loc[transactions['TransactionID']==102,'Amount']=165
display(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

**loc is used to find TransactionID 102 and change its Amount from 150 to 165. The remaining rows stay unchanged.**

b) Add a new column 'Discount' by calculating 10% of the 'Amount'.

In [35]:
transactions['Discount']=transactions['Amount']*0.10
display(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

**A new column named Discount is created by multiplying each transaction amount by 0.10, which calculates a 10% discount.**

c) Remove the row with TransactionID 109.

In [36]:
transactions=transactions[transactions['TransactionID']!=109]
display(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

**Here !=109 means not equal to 109.The code keeps all rows except TransactionID 109 and saves the result back into transactions.**

d) Delete the 'Discount' column from the DataFrame.

In [37]:
transactions=transactions.drop(columns=['Discount'])
display(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400

**drop(columns=['Discount']) remove the Discount column.The updated DataFrame is saved back into transactions.**